apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo-gke

spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellogo-gke
  template:
    metadata:
      labels:
        app: hellogo-gke
    spec:
      containers:
      - name: hellogo-gke
        image: hellogo-gke:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
          value: "8080"