apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo-gke

spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellogo-gke
  template:
    metadata:
      labels:
        app: hellogo-gke
    spec:
      containers:
      - name: hellogo
        image: hellogo:latest
        ports:
        - containerPort: 8080